# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c623e982c8a86af194d854d54f30c08e234a7be468ab4429ad6bb19a256b1a44228aaa35e97a6c870cb5a0c39f0de9a2f3778ea0331ace6457d7bcf1d9c49a45

test:
  secret_key_base: ce7e1c865cc409b8c6667dfca6724e59598561f38d99c8051b04f16a17ac16c08c2982bd5e3edb1bc5baa0a7bdd4513120fca8b9e04377e81cbf6c55ea23f790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
