# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37bf70b3e02d8f973d4040f988fa7d8a91fffbd8a7a6b9845afd7031c3bc2bd9087d5771ddf4abece21d8620a95ea61c079e20b86205a3f4e06d8efc181fb46d

test:
  secret_key_base: 93c239fd59c9768729aa79e06283aa97d8bac427ce4f57113a7f802c65757fd2ce13d27803d5f8f9f541c77dff966c9c04b40c39ecf63f780663a189745698f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
